<?php
$labels = array();
$labels['aliases'] = 'Alias';
$labels['autoreply'] = "Envoyer la notification";
$labels['autoreplybutton'] = 'Enregistrer';
$labels['autoreplymessage'] = 'Message de la réponse automatique';
$labels['autoreplysubject'] = 'Sujet de la réponse automatique';
$labels['failed'] = 'Échec de la configuration de réponse automatique!';
$labels['forward'] = 'Paramètres de transfert';
$labels['forwardingaddresses'] = 'Transférer le courrier à';
$labels['keepcopy'] = 'Conserver une copie du courrier';
$labels['mailforward'] = 'Réexpédition du courrier';
$labels['outofoffice'] = 'Notification de vacances (absence du bureau)';
$labels['separate_alias'] = 'Séparez chaque adresse alias par une virgule';
$labels['separate_forward'] = 'Séparez chaque adresse de transfert par une virgule';
$labels['success_changed'] = 'Les paramètres de réponse automatique ont été modifiés avec succès';
$labels['vacation'] = 'Réponse automatique';
// Button text
$labels['aliasesbutton'] = 'Récupérer les alias';
?>
